const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={page:'home',listening:false,memory:JSON.parse(localStorage.getItem('jarvis_memory')||'[]'),history:JSON.parse(localStorage.getItem('jarvis_history')||'[]'),settings:JSON.parse(localStorage.getItem('jarvis_settings')||'{}')};
const save=()=>{localStorage.setItem('jarvis_memory',JSON.stringify(state.memory));localStorage.setItem('jarvis_history',JSON.stringify(state.history));localStorage.setItem('jarvis_settings',JSON.stringify(state.settings));$('#memoryCount').textContent=`${state.memory.length} ITEMS`};
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function page(p){state.page=p;$$('.page').forEach(x=>x.classList.toggle('active',x.id===p));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));if(p==='memory')renderMemory();if(p==='history')renderHistory()}
$$('.nav[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));
function setCore(s,text=''){const c=$('#core');c.className='core '+s;$('#coreState').textContent=s? s.toUpperCase():'READY';if(text)$('#transcript').textContent=text}
function addMsg(text,who='ai'){const d=document.createElement('div');d.className='msg '+(who==='user'?'user':'ai');d.innerHTML=`<small>${who==='user'?'YOU':'JARVIS'}</small>${escapeHtml(text).replace(/\n/g,'<br>')}`;$('#messages').appendChild(d);$('#messages').scrollTop=$('#messages').scrollHeight}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function localReply(q){const l=q.toLowerCase();if(l.includes('time')||q.includes('समय')||q.includes('टाइम'))return `अभी ${new Date().toLocaleTimeString('hi-IN',{hour:'2-digit',minute:'2-digit'})} बजे हैं।`;if(l.includes('hello')||l.includes('hi')||q.includes('हैलो')||q.includes('नमस्ते'))return 'नमस्ते। JARVIS online है। मैं आपकी मदद के लिए तैयार हूँ।';if(l.includes('what can you do')||q.includes('क्या कर'))return 'मैं voice input, chat, local memory, history और browser-based assistant features संभाल सकता हूँ। Gemini API जोड़ने पर मेरी reasoning और knowledge capabilities बढ़ेंगी।';if(l.includes('settings')){page('settings');return 'Settings खोल दी गई हैं।';}return 'मैं अभी local demo mode में हूँ। Gemini API जोड़ने के बाद मैं इस संदेश का AI-generated उत्तर दे सकता हूँ।'}
async function ask(q){if(!q.trim())return;page('chat');addMsg(q,'user');setCore('thinking','Processing…');const key=state.settings.apiKey;if(key){try{const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key='+encodeURIComponent(key),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:`You are JARVIS, a concise professional personal AI assistant. Understand Hindi, Hinglish and English. User says: ${q}`}]}]})});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||'API error');const a=j?.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||'No response.';addMsg(a);speak(a);log(q,a);setCore('speaking','Speaking…');setTimeout(()=>setCore(''),1200);return}catch(e){toast('Gemini API error — local mode used')}}const a=localReply(q);addMsg(a);speak(a);log(q,a);setCore('speaking','Speaking…');setTimeout(()=>setCore(''),1200)}
function log(q,a){state.history.unshift({q,a,t:new Date().toISOString()});state.history=state.history.slice(0,50);save()}
$('#chatForm').onsubmit=e=>{e.preventDefault();const q=$('#chatInput').value;$('#chatInput').value='';ask(q)};
$$('.quick button').forEach(b=>b.onclick=()=>ask(b.dataset.command));
$('#clearChat').onclick=()=>{$('#messages').innerHTML='';toast('Conversation cleared')};
function renderMemory(){$('#memoryList').innerHTML=state.memory.length?state.memory.map((m,i)=>`<div class="memory-card"><b>${escapeHtml(m.title)}</b><p>${escapeHtml(m.text)}</p><button onclick="deleteMemory(${i})">Delete</button></div>`).join(''):'<div class="panel" style="padding:18px;color:#7897a1;font-size:11px">No memories yet.</div>'}
window.deleteMemory=i=>{state.memory.splice(i,1);save();renderMemory()};$('#addMemory').onclick=()=>{const title=prompt('Memory title');if(!title)return;const text=prompt('What should JARVIS remember?');if(!text)return;state.memory.push({title,text});save();renderMemory();toast('Memory saved')};
function renderHistory(){$('#historyList').innerHTML=state.history.length?state.history.map(h=>`<div class="history-card"><b>${escapeHtml(h.q)}</b><p>${escapeHtml(h.a)}</p><small>${new Date(h.t).toLocaleString()}</small></div>`).join(''):'<div class="panel" style="padding:18px;color:#7897a1;font-size:11px">No mission logs yet.</div>'}$('#clearHistory').onclick=()=>{state.history=[];save();renderHistory();toast('History cleared')};
function speak(t){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang=state.settings.language==='en'?'en-IN':'hi-IN';u.rate=.95;u.pitch=.95;u.onstart=()=>$('#voiceStatus').textContent='SPEAKING';u.onend=()=>$('#voiceStatus').textContent='READY';speechSynthesis.speak(u)}
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let rec;if(SR){rec=new SR();rec.lang='hi-IN';rec.interimResults=false;rec.onstart=()=>{state.listening=true;setCore('listening','Listening…');$('#voiceStatus').textContent='LISTENING'};rec.onresult=e=>{const t=e.results[0][0].transcript;$('#transcript').textContent=t;ask(t)};rec.onerror=()=>{state.listening=false;setCore('');$('#voiceStatus').textContent='READY';toast('Microphone error')};rec.onend=()=>{state.listening=false;$('#voiceStatus').textContent='READY'}}
function listen(){if(!rec){toast('Speech recognition is not supported in this browser');return}try{rec.lang=state.settings.language==='en'?'en-IN':'hi-IN';rec.start()}catch(e){}}
$('#core').onclick=listen;$('#navVoice').onclick=listen;
$('#saveSettings').onclick=()=>{state.settings={assistantName:$('#assistantName').value||'JARVIS',language:$('#language').value,apiKey:$('#apiKey').value};save();toast('Settings saved');if(rec)rec.lang=state.settings.language==='en'?'en-IN':'hi-IN'};
(function init(){state.settings={assistantName:'JARVIS',language:'hi',...state.settings};$('#assistantName').value=state.settings.assistantName;$('#language').value=state.settings.language;$('#apiKey').value=state.settings.apiKey||'';save();renderMemory();renderHistory();addMsg('System online. नमस्ते — JARVIS तैयार है।','ai')})();
